### ISSUE TITLE
Clarification for “interaction with arguments”

### ISSUE THREAD

**Issue by addaleax** [Fishrock123/proposal-const-function-arguments#1]
Under [Interaction with the `arguments` object](https://github.com/Fishrock123/proposal-const-function-arguments#interaction-with-the-arguments-object), it isn’t really clear to me:

- What happens in strict mode?
- What do the (fake) property descriptors look like? Is `writable: false` in those cases and/or would that be the simplest way to achieve the behaviour described in that section?

**Comment by ljharb** [comment]
In strict mode, the `arguments` object is entirely decoupled from the argument bindings; I wouldn't expect const argument bindings to have any impact on the `arguments` object (which is what that section says to my reading).

In sloppy mode, assigning to the binding updates the arguments object, and vice versa: the implication here is that mutating the arguments object in sloppy mode would not update a const binding (you wouldn't be able to reassign the binding, so the reverse is straightforward)

**Comment by Fishrock123** [comment]
Perhaps I should clarify at the top, the implication is that this:

```js
fn(1)

function fn (const a) {
  // a is 1

  arguments[0] = 2
  // a is 1
  // arguments[0] is 2
}
```

Would act like so, in either mode:

```js
fn(1)

function fn (_a) {
  const a = _a
  // a is 1

  arguments[0] = 2
  // a is 1
  // arguments[0] is 2
}
```

**Comment by addaleax** [comment]
Okay, thanks, this was helpful :)
